services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: conversation_history_development
  web:
    platform: linux/x86_64
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/conversation_history_development
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: true
    stdin_open: true
    tty: true
volumes:
  postgres_data:
